### ISSUE TITLE
Font test

### ISSUE THREAD

**Issue by GehPlatVwaard** [veraPDF/veraPDF-wcag-algs#120] opened 2021-11-28 08:09 UTC
[This document ](https://github.com/veraPDF/veraPDF-wcag-algs/files/7613056/VAL_Nieuwsbrief.Masterplan.Centrum_juni21-pad.pdf) fails a font test: Syntax-Roman.
VeraPDF reports: If the FontDescriptor dictionary of an embedded Type 1 font contains a CharSet string, then it shall list the character names of all glyphs present in the font program, regardless of whether a glyph in the font is referenced or used by the PDF or not. 

It looks comparable to issue #90: possibly you can ignore it for the purposes of WCAG validation (in front end)?

**Comment by bdoubrov** [comment] 2021-12-01 08:39
Yes, both CharSet (for so-called simple fonts) and CIDSet (for composite fonts) requirements are a part of PDF/UA-1 validation, but will be disabled for WCAG. So, I mark this issues as duplicate of #90

**Closed** 2021-12-01 08:39 UTC
Labels: duplicate
